name: Publish site
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package.json"
      - "src/**"
      - "pages/**"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://api.workinpublic.io
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_FRONTEND_API: clerk.workinpublic.io

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy
